### DISCUSSION TITLE
Middleware Type not showing correctly for some types (last Commit effc0b1)

### DISCUSSION THREAD

**Discussion by oidebrett** [hhftechnology/middleware-manager#16] [General]
In the latest dev branch Commit effc0b1, some new middleware types are not showing correctly when editing middlewares. I tried types of replacepathregex and redirectregex (from a new template middleware I defined). I know this is a development branch so not to expect 100% working. Just wanted to let you know.

**Comment by hhftechnology** [comment]
let me know the lists of middleware which are not working so i can check

**Comment by oidebrett** [comment]
Try any of the regex ones and you will see the drop-down is incorrect

**Comment by oidebrett** [comment]
I found the root cause of this issue. Its actually a templates.yml entry error

```
  - id: nextcloud-dav
    name: Nextcloud WebDAV Redirect
    type: replacepathregex
    config:
      regex: "^/.well-known/ca(l|rd)dav"
      replacement: "/remote.php/dav/"

```
should be
```
  - id: nextcloud-dav
    name: Nextcloud WebDAV Redirect
    type: replacePathRegex
    config:
      regex: "^/.well-known/ca(l|rd)dav"
      replacement: "/remote.php/dav/"

```

Apparently case matters in middleware types :)
