### ISSUE TITLE
Bypass rules

### ISSUE THREAD

**Issue by ahmaddxb** [hhftechnology/middleware-manager#52]
Is there a way I can make these from the UI?

It can't be added manually to resource-overrides.yml as it is overwritten. 

nzb360-overides.yml
```
http:
    routers:
        4-router-auth-auth-bypass:
            entryPoints:
                - websecure
            priority: 100
            rule: "Host(`sonarr.{{env `DOMAINNAME0`}}`) && (Header(`X-Api-Key`, `{{env `SONARR_API_KEY`}}`) || Query(`apikey`, `{{env `SONARR_API_KEY`}}`))"
            service: "4-service@http"
            tls:
                certResolver: "letsencrypt"

        7-router-auth-auth-bypass:
            entryPoints:
                - websecure
            priority: 100
            rule: "Host(`radarr.{{env `DOMAINNAME0`}}`) && (Header(`X-Api-Key`, `{{env `RADARR_API_KEY`}}`) || Query(`apikey`, `{{env `RADARR_API_KEY`}}`))"
            service: "7-service@http"
            tls:
                certResolver: "letsencrypt"

        18-router-auth-auth-bypass:
            entryPoints:
                - websecure
            priority: 100
            rule: "Host(`nzbget.{{env `DOMAINNAME0`}}`) && (Header(`authorization`, `Basic {{env `NZBGET_API_KEY`}}`))"
            service: "18-service@http"
            tls:
                certResolver: "letsencrypt"
          
        19-router-auth-auth-bypass:
            entryPoints:
                - websecure
            priority: 100
            rule: "Host(`qbittorrent.{{env `DOMAINNAME0`}}`) && (PathPrefix(`/api/v2`))"
            service: "19-service@http"
            tls:
                certResolver: "letsencrypt"
```
